Add ref to buttons
hypothesis/frontend-shared pull request #28
Opened 2021-04-23 00:43 UTC by LMS007

In LMS, we need to pass along a button `ref` in order to set focus on the button when a dialog opens. In order to pass along the ref, we need to forward the ref down to the HTML component. Preact docs recommend using forwardRef

https://preactjs.com/guide/v10/switching-to-preact/#forwardref

2021-04-23 00:44 UTC, LMS007 commented on src/components/test/buttons-test.js
> +      assert.isTrue(buttonRef.current instanceof Node);
This would fail if we don't forward the ref because the object would be a Preact component, not a Node.

2021-04-26 14:19 UTC, lyzadanger commented
@LMS007 It appears that this PR branch contains the changes from #27 . Can you rebase or otherwise clarify?

2021-04-26 18:16 UTC, LMS007 commented
> @LMS007 It appears that this PR branch contains the changes from #27 . Can you rebase or otherwise clarify?

done

2021-04-27 12:32 UTC, lyzadanger requested changes
This seems mostly innocuous, but I'd like to see a test for the `undefined` path of `buttonRef` just to sew up some loose ends.

2021-04-27 12:32 UTC, lyzadanger commented on src/components/buttons.js
> +      ref={buttonRef}
What is the behavior of this component if `buttonRef` is `undefined`?

2021-04-27 14:55 UTC, lyzadanger approved these changes
👍🏻

2021-04-27 15:31 UTC, merged