Establish Pattern Library in this repo
hypothesis/frontend-shared pull request #36
Opened 2021-04-27 18:11 UTC by lyzadanger

This (very large) PR contains all of the needed bits and bobs to get the pattern library going (source, build, bundle, serve) in this repository, and leaves some "edges" that will allow the pattern library to be extended by users of the package.

**Don't panic.** The vast majority of these changes are boilerplate or code copied over from the `client` repo. I've done my best to break changes down into reasonable commits. I'd recommend approaching this work on a commit-by-commit basis:

* _Add pattern-library source JS and SASS_: copied from client; only paths are adjusted. No human review needed.
* _Add icons needed by pattern library_: copy-pasting SVG source for a few icons needed by the current patterns, along with a simple `icons` module for registering pattern-library icons. This should only require a cursory review.
* _Add entry points for pattern library_: A slight rework of the client's existing pattern-library entry point into two modules: `index` and `app`, where `index` is the entry point for local bundling and `app` can be used by package users to extend the pattern library. Not much code here, but could use a review.
* _Add dependencies and scripts..._: I isolated dependencies into this commit and copied over gulp scripts from other repos. Should not need human review.
* _Add templates and webserver script..._: A couple of `mustache` templates and a module for serving the pattern library with `express`. Review me, please :).
* _Update gulpfile..._: Significant update to gulpfile to build, bundle, serve and watch pattern-library assets. The approach for these tasks was copied from other apps (i.e. I'm not inventing anything new here). Review me please.
* _Add `dev` target_: Tiny commit to add `make dev`.

### Known rough edges

* The pattern library currently doesn't serve at the root level of the port it's served on, but instead is nested under `ui-playground`. **This is annoying**. I was having some woes with the `router` when I tried to serve at web root:

    <img width="1588" alt="Screen Shot 2021-04-27 at 1 09 44 PM" src="https://user-images.githubusercontent.com/439947/116290530-8c278a80-a761-11eb-9cca-b882c14f4abd.png">
    
    And didn't feel like tracking it down just now. For now, the landing page provides a simple link to the pattern library.
* The location of the `serve` module for the pattern library is temporary and almost certain to move. It doesn't belong with packaged source, but instead, likely, with the build/tooling of the package.
* How and if the bundled JS and CSS for the pattern library should be published with the package. 
* What default port to use here. I chose `4001` out of the air.

### Try it out

Check out/pull this branch and run `make dev` and open the logged URI in your browser.

### Let me know...

If you want me to break this into multiple PRs. I can do so if it's helpful.

Part of #20

2021-04-27 18:15 UTC, lyzadanger commented on .eslintignore
> +build/**
Don't lint or prettify stuff output to `build`...

2021-04-27 18:15 UTC, lyzadanger commented on Makefile
> +	@echo "make dev               Run the pattern library app in a development server"
Adding `make dev` target to act more like other projects.

2021-04-27 18:15 UTC, lyzadanger commented on gulpfile.js
> +('use strict');
REVIEW ME (changes based on other projects).

2021-04-27 18:15 UTC, lyzadanger commented on scripts/gulp/create-bundle.js
> +/* eslint-env node */
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on scripts/gulp/create-style-bundle.js
> +'use strict';
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on scripts/gulp/minify-stream.js
> +/* eslint-env node */
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/components/PatternPage.js
> +import { toChildArray } from 'preact';
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/components/PlaygroundApp.js
> +import { SvgIcon } from '../../components/SvgIcon';
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/components/patterns/SharedButtonPatterns.js
> +import { IconButton, LabeledButton, LinkButton } from '../../../';
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/icons.js
> +// @ts-nocheck
NEW, but based on other "icons" modules in other projects.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/index.js
> +// Entry point for default pattern-library bundle
NEW. Separate bundle entry point.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/router.js
> +import { useEffect, useMemo, useState } from 'preact/hooks';
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/templates/index.mustache
> +<!DOCTYPE html>
TEMPORARY: because the pattern library is not served at the web root.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/templates/pattern-library.mustache
> +<!DOCTYPE html>
COPIED.

2021-04-27 18:15 UTC, lyzadanger commented on src/pattern-library/util/jsx-to-string.js
> +/**
COPIED. No review needed.

2021-04-27 18:15 UTC, lyzadanger commented on styles/pattern-library.scss
> +@use 'base/reset';
COPIED. No review needed; paths at top updated.

2021-04-27 18:18 UTC, lyzadanger commented on gulpfile.js
> +function runKarma(done) {
This already existed but I moved it within the module.

2021-04-27 18:18 UTC, lyzadanger commented on gulpfile.js
> +gulp.task('build-test-css', done => {
I renamed this task because we have other CSS-building needs now.

2021-04-27 18:19 UTC, lyzadanger commented on src/pattern-library/.eslintrc
> +{
COPIED.

2021-04-27 18:19 UTC, lyzadanger commented on src/pattern-library/app.js
> +// Entry point for extending the pattern library
This is...sorta new but mostly just adapted. Wraps the app startup for use by other projects, eventually.

2021-04-27 18:58 UTC, lyzadanger commented
See also: https://github.com/hypothesis/client/pull/3348

2021-04-27 19:02 UTC, LMS007 requested changes
Thanks Lyza, lots of moving parts here, and this mostly worked for me right away, but I did have some questions. Looks like I got a mine type error and the styles did not load. I will look into that later--it may be local to me.

![Screen Shot 2021-04-27 at 11 31 52 AM](https://user-images.githubusercontent.com/3939074/116294054-60e67080-a74c-11eb-9b12-441d60187401.png)

It looks like these new tasks are completely orthogonal to the tasks that build the /lib folder. Is that correct? I believe we could have gone either way and used lib/ as a base for the bundling OR, just use the src/ files directly and transpile everything specifically for the pattern lib. I feel like the latter is more clear so I think that's a good choice. Is that correct? I did had an older PR that attempted to prep some of this but it looks like its irreverent now.

https://github.com/hypothesis/frontend-shared/pull/6

Secondly, I don't see a use for this to exist outside "development" so I'm not even sure we need a  the concept of "production". I believe this is always going to be dev right? Unless we host this pattern lib somewhere live, but even so, it would likely be helpful to not have minified code even in that case imo. If thats true, I wonder if we can trim down some of the checks for IS_PRODUCTION_BUILD and just never minify the code.  The concept of minify implies that could be used in production so that's a little confusing to me.

I'd also like to see very clear distinction between the tasks that are bundling the pattern lib and the ones that create the lib/. At present we have a script called `build-js` in package.json and a task called `build-js` in gulpfile and they do different things. So that just means `yarn build-js` and `gulp build-js` don't do the same thing here.  I'd like to see a different name so we can clearly understand the discussion between release bundling into the lib/ and dev bundling for the express server inside of /build

Finally, I think the pattern lib code may not be well suited for the /src folder. The intention of the src folder was for the things that this repo exports. The pattern lib is more an internal tool to visualize the things. At present, when you run `yarn build-js` it also transpiles the pattern lib files and you can see them inside /lib which we don't want. I think instead of making complex rules for ignoring files, we just need a clear distinction  between files for /lib and the other stuff. Perhaps we can just have a root level folder called `pattern-library`?

2021-04-27 19:04 UTC, lyzadanger commented
> Finally, I think the pattern lib code may not be well suited for the /src folder. The intention of the src folder was for the things that this repo exports.

The `pattern-library` source _is_ exported. We'll need to use it, e.g. from the client.

2021-04-27 19:05 UTC, lyzadanger commented
> At present, when you run yarn build-js it also transpiles the pattern lib files and you can see them inside /lib which we don't want.

I'm pretty sure we do?

2021-04-27 19:07 UTC, lyzadanger commented
> It looks like these new tasks are completely orthogonal to the tasks that build the /lib folder. Is that correct?

I'm not sure what this question means, exactly.

2021-04-27 19:11 UTC, lyzadanger commented
@LMS007 I want to correct what I think is a bit of a misunderstanding: the pattern library is not private/internal to this project. It will be imported and extended by other projects—immediately in the client, for example. The intention is that the pattern library source should be part of the published package, but should have a different entry point than the "main" part of the package, as it won't be used by all package consumers. I delineated in the PR description that there are a few rough edges yet in terms of what is bundled and packaged, and will continue to tighten it up. The `serve` module needs to move out of `src`, for example.

2021-04-27 19:13 UTC, lyzadanger commented
> Looks like I got a mine type error and the styles did not load. I will look into that later--it may be local to me.

We should debug this. What browser are you using and what URL are you attempting to load in your browser? There are some odd "spaces" in the URLs in the console that seem a little bit fishy, but it's also possible that the `express` static route handling needs to be tweaked here; I can't tell right off.

2021-04-27 19:24 UTC, lyzadanger commented
@LMS007 I've reproduced the CSS issue and it looks like a race condition/ordering problem with some gulp tasks. Working on a fix for yah/us.

2021-04-27 19:27 UTC, lyzadanger commented
@LMS007 I pushed a commit that renames some `gulp` tasks for clarity and fixes the CSS-bundling ordering issue you ran into.

2021-04-27 20:42 UTC, LMS007 commented
I believe I had a misunderstanding about the pattern lib expectations. I thought It was for internal usage, but if we are going to export it, then ignore my suggestions about separating it from /lib.

2021-04-28 12:38 UTC, lyzadanger commented
Update: I have rebased this PR on #37, which breaks out the rote copy-n-paste of pattern-library source so that it isn't cluttering up this branch.

2021-04-28 14:27 UTC, lyzadanger commented
This PR is superseded by #39 (and also #37 and #38).

2021-04-28 14:27 UTC, closed without merging